/**
 * /api/images — R2-backed image routes (Phase 1).
 *
 *   GET    /api/images          → list objects (public)
 *   PUT    /api/images          → staff only; binary body, stored as
 *                               folder/timestamp-rand.jpg, returns { url }
 *   DELETE /api/images?key=…    → staff only; deletes one object
 *   GET    /api/img/<key>       → serve one object (public)
 *
 * Uploaded objects are always served from this same-origin route, so the
 * { url } returned by PUT works on whatever domain the site is deployed to —
 * workers.dev, a future custom domain, or localhost — with no configuration.
 * If IMAGE_PUBLIC_BASE_URL is set (R2 custom domain), PUT returns that
 * instead and /api/img stays as a fallback.
 */

import { badRequest, requireStaff, unauthorized } from "./auth";
import type { Env } from "./index";

/** Only known upload folders are accepted, so keys stay predictable. */
const ALLOWED_FOLDERS = new Set(["news", "gallery", "events", "site"]);

export async function handleImages(
  request: Request,
  env: Env,
): Promise<Response> {
  // R2 may be unbound (bucket not yet enabled/created in the account).
  // Fail softly so the rest of the site and admin portal keep working.
  if (!env.IMAGES) {
    return json(
      {
        error: "storage_unavailable",
        detail: "R2 is not configured — enable R2 in the Cloudflare dashboard, create the hope-images bucket, and redeploy.",
      },
      503,
    );
  }

  const { method } = request;
  const url = new URL(request.url);

  if (method === "GET") return listImages(env);

  if (method === "PUT") return putImage(request, env);

  if (method === "DELETE") {
    if (!(await requireStaff(request, env))) return unauthorized();
    const key = url.searchParams.get("key");
    if (!key) return badRequest("Missing ?key= (the R2 object key)");
    await env.IMAGES.delete(key);
    return json({ deleted: key });
  }

  return new Response(JSON.stringify({ error: "method_not_allowed" }), {
    status: 405,
    headers: { allow: "GET, PUT, DELETE" },
  });
}

/**
 * GET /api/img/<key> — serve one R2 object publicly.
 * Keys are generated by putImage (`folder/timestamp-rand.jpg`), so the
 * whitelist keeps arbitrary object probing impossible.
 */
export async function serveImage(
  request: Request,
  env: Env,
  key: string,
): Promise<Response> {
  if (!env.IMAGES) return new Response("Not found", { status: 404 });
  if (!/^[a-z0-9-]+\/[\w.-]+$/.test(key)) {
    return new Response("Not found", { status: 404 });
  }
  const object = await env.IMAGES.get(key);
  if (!object) return new Response("Not found", { status: 404 });

  const headers = new Headers();
  object.writeHttpMetadata(headers);
  headers.set("etag", object.httpEtag);
  // Keys embed an upload timestamp, so their content never changes —
  // cache for a year at the edge and in browsers.
  headers.set("cache-control", "public, max-age=31536000, immutable");
  return new Response(object.body, { headers });
}

async function listImages(env: Env): Promise<Response> {
  const listed = await env.IMAGES.list();
  return json({
    images: listed.objects.map((o) => ({
      key: o.key,
      size: o.size,
      uploaded: o.uploaded.toISOString(),
    })),
    truncated: listed.truncated,
  });
}

async function putImage(request: Request, env: Env): Promise<Response> {
  if (!(await requireStaff(request, env))) return unauthorized();

  const url = new URL(request.url);
  const folder = url.searchParams.get("folder") ?? "gallery";
  if (!/^[a-z0-9-]+$/.test(folder) || !ALLOWED_FOLDERS.has(folder)) {
    return badRequest(
      `folder must be one of: ${[...ALLOWED_FOLDERS].join(", ")}`,
    );
  }
  if ((request.headers.get("content-length") ?? "1") === "0") {
    return badRequest("Empty body — send the image bytes");
  }

  const body = await request.arrayBuffer();

  // Callers normally let the Worker mint a fresh key. The migration script
  // (scripts/migrate-images-to-r2.mjs) passes ?key= to preserve the original
  // object key, so URLs stored in D1 keep working after the copy.
  const requestedKey = url.searchParams.get("key");
  const key =
    requestedKey && /^[a-z0-9-]+\/[\w.-]+$/.test(requestedKey)
      ? requestedKey
      : `${folder}/${Date.now()}-${Math.random().toString(36).slice(2, 10)}.jpg`;

  await env.IMAGES.put(key, body, {
    httpMetadata: { contentType: "image/jpeg" },
  });

  // Root-relative by default so URLs keep working across domains (the site
  // may be reached via workers.dev AND a custom domain). lib/db.ts passes
  // root-relative paths through unchanged and browsers resolve them against
  // the page origin, which is exactly where /api/img lives.
  const base = env.IMAGE_PUBLIC_BASE_URL?.replace(/\/+$/, "") ?? "";
  const publicUrl = base ? `${base}/${key}` : `/api/img/${key}`;
  return json({ url: publicUrl, key }, 201);
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}
